Q = 100
EPSILON = 0.1
NB_EPOCHS = 600
TAILLE_BATCH = 4
NB_DONNEES_GENEREES = 9
NB_ITER_GIBBS = 2000
CARACTERES_ENTRAINEMENT = ['4', '5', '6']
MNIST_ENTRAINEMENT = [4, 5, 6]
SPECS_ENTRAINEMENT = {'nbepochs': NB_EPOCHS, 'taillebatch': TAILLE_BATCH, 'nbcaracteres': len(CARACTERES_ENTRAINEMENT)}
SPECS_ENTRAINEMENT_MNIST = {'nbepochs': NB_EPOCHS, 'taillebatch': TAILLE_BATCH,
                            'nbcaracteres': len(CARACTERES_ENTRAINEMENT), 'mnist': True}
COMMENCER_PAR_H_GIBBS = False
PREMIERE_EPOCH_PLOT = 50
